import type { Message, Contact, Thread, PlatformConnection } from "./types"

// ── Contacts ────────────────────────────────────────────

const contacts: Record<string, Contact> = {
  sarah: {
    id: "c1",
    name: "Sarah Chen",
    email: "sarah.chen@sequoia.vc",
    platform: "gmail",
    isVip: true,
    relationship: "Investor",
    conversationCount: 12,
  },
  marcus: {
    id: "c2",
    name: "Marcus Rivera",
    email: "marcus@company.com",
    platform: "slack",
    isVip: false,
    relationship: "Manager",
    conversationCount: 47,
  },
  elena: {
    id: "c3",
    name: "Elena Kowalski",
    platform: "telegram",
    isVip: false,
    relationship: "Client",
    conversationCount: 8,
  },
  jake: {
    id: "c4",
    name: "Jake Morrison",
    email: "jake@designlabs.io",
    platform: "gmail",
    isVip: false,
    relationship: "Vendor",
    conversationCount: 5,
  },
  priya: {
    id: "c5",
    name: "Priya Patel",
    platform: "slack",
    isVip: false,
    relationship: "Teammate",
    conversationCount: 93,
  },
  alex: {
    id: "c6",
    name: "Alex Drummond",
    platform: "discord",
    isVip: false,
    relationship: "Community Lead",
    conversationCount: 22,
  },
  nina: {
    id: "c7",
    name: "Nina Zhang",
    email: "nina@techcorp.com",
    platform: "gmail",
    isVip: true,
    relationship: "Board Member",
    conversationCount: 6,
  },
  tom: {
    id: "c8",
    name: "Tom Hendricks",
    platform: "slack",
    isVip: false,
    relationship: "Product Lead",
    conversationCount: 31,
  },
  maya: {
    id: "c9",
    name: "Maya Okonkwo",
    platform: "telegram",
    isVip: false,
    relationship: "Advisor",
    conversationCount: 4,
  },
  ryan: {
    id: "c10",
    name: "Ryan Fletcher",
    platform: "discord",
    isVip: false,
    relationship: "Developer",
    conversationCount: 15,
  },
  lisa: {
    id: "c11",
    name: "Lisa Park",
    email: "lisa@acmeventures.com",
    platform: "gmail",
    isVip: false,
    relationship: "Recruiter",
    conversationCount: 2,
  },
  daniel: {
    id: "c12",
    name: "Daniel Cruz",
    platform: "slack",
    isVip: false,
    relationship: "DevOps Lead",
    conversationCount: 18,
  },
  sam: {
    id: "c13",
    name: "Sam Whitfield",
    email: "sam@legalteam.co",
    platform: "gmail",
    isVip: false,
    relationship: "Legal Counsel",
    conversationCount: 3,
  },
  kate: {
    id: "c14",
    name: "Kate Bennett",
    platform: "slack",
    isVip: false,
    relationship: "Designer",
    conversationCount: 26,
  },
  omar: {
    id: "c15",
    name: "Omar Farouk",
    platform: "telegram",
    isVip: false,
    relationship: "Co-founder",
    conversationCount: 67,
  },
  jess: {
    id: "c16",
    name: "Jessica Tran",
    platform: "discord",
    isVip: false,
    relationship: "Moderator",
    conversationCount: 41,
  },
  wei: {
    id: "c17",
    name: "Wei Liu",
    platform: "slack",
    isVip: false,
    relationship: "Customer",
    conversationCount: 7,
  },
}

// ── Helper ──────────────────────────────────────────────

function ago(minutes: number): Date {
  return new Date(Date.now() - minutes * 60 * 1000)
}

// ── Messages ────────────────────────────────────────────

export const MOCK_MESSAGES: Message[] = [
  // ─ URGENT (3) ─────────────────────────────────────────
  {
    id: "m1",
    platform: "gmail",
    sender: contacts.sarah,
    subject: "Q3 Investor Update — Need by Friday",
    preview: "Hey, just following up on the Q3 investor update deck. The board meeting is Friday and we need the final numbers by EOD Thursday at the latest...",
    content: "Hey,\n\nJust following up on the Q3 investor update deck. The board meeting is Friday and we need the final numbers by EOD Thursday at the latest.\n\nSpecifically, we need:\n- Revenue figures for Q3\n- Updated burn rate\n- Revised growth projections\n\nLet me know if you need any help pulling this together. This is time-sensitive.\n\nBest,\nSarah",
    threadId: "t1",
    priority: "urgent",
    priorityScore: 95,
    priorityReason: "VIP investor contact + keyword 'deadline' + time-sensitive request with explicit due date",
    sentiment: "neutral",
    aiContextNote: "Investor contact \u00b7 hasn't messaged in 30 days",
    receivedAt: ago(8),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m2",
    platform: "slack",
    sender: contacts.marcus,
    subject: "Production is down",
    preview: "🚨 Production API is returning 503s. Customer complaints coming in. Need someone on this NOW.",
    content: "🚨 Production API is returning 503s across all endpoints. Customer complaints coming in through support channels.\n\nNeed someone on this NOW. @oncall team has been paged but no response in 15 minutes.\n\nLooks like it started after the 2:30 PM deployment. We may need to rollback.",
    threadId: "t2",
    priority: "urgent",
    priorityScore: 98,
    priorityReason: "Manager + production incident + keyword 'down' + immediate action required",
    sentiment: "tense",
    sentimentAdvice: "Acknowledge the urgency before responding. Focus on immediate actions and status updates.",
    aiContextNote: "Your manager \u00b7 production incident pattern",
    receivedAt: ago(2),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m3",
    platform: "telegram",
    sender: contacts.elena,
    subject: "Contract issue — urgent",
    preview: "There's a discrepancy in the contract terms we discussed. Clause 4.2 doesn't match what was agreed in our last call. We need to resolve this before signing tomorrow.",
    content: "Hi,\n\nThere's a discrepancy in the contract terms we discussed. Clause 4.2 about the payment schedule doesn't match what was agreed in our last call.\n\nSpecifically:\n- We agreed on NET-30 but the contract says NET-60\n- The penalty clause was supposed to be removed\n\nWe need to resolve this before signing tomorrow morning. Can you get legal to review and send a corrected version today?\n\nThanks,\nElena",
    threadId: "t3",
    priority: "urgent",
    priorityScore: 88,
    priorityReason: "Client relationship + contract keyword + time-sensitive with tomorrow deadline",
    sentiment: "tense",
    sentimentAdvice: "Acknowledge their concern about the discrepancy before jumping to solutions.",
    aiContextNote: "Client \u00b7 active contract negotiation \u00b7 8 past conversations",
    receivedAt: ago(25),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },

  // ─ ACTION NEEDED (8) ──────────────────────────────────
  {
    id: "m4",
    platform: "gmail",
    sender: contacts.jake,
    subject: "Invoice #4521 — Payment Overdue",
    preview: "Hi, this is a reminder that invoice #4521 for $12,400 is now 15 days overdue. Please process payment at your earliest convenience.",
    content: "Hi,\n\nThis is a friendly reminder that invoice #4521 for $12,400 is now 15 days overdue. Our records show it was due on March 8th.\n\nCould you please process payment at your earliest convenience? I've attached the invoice again for reference.\n\nIf there's an issue with the invoice, happy to discuss.\n\nBest regards,\nJake Morrison\nDesignLabs.io",
    threadId: "t4",
    priority: "action_needed",
    priorityScore: 72,
    priorityReason: "Vendor + payment/invoice keyword + overdue action required",
    sentiment: "neutral",
    aiContextNote: "Vendor \u00b7 payment overdue 15 days",
    receivedAt: ago(45),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m5",
    platform: "slack",
    sender: contacts.priya,
    subject: "PR Review: Auth refactor",
    preview: "Hey, can you review my PR when you get a chance? It's the auth middleware refactor we discussed. ~400 lines changed.",
    content: "Hey, can you review my PR #342 when you get a chance?\n\nIt's the auth middleware refactor we discussed last sprint. About 400 lines changed, mostly moving logic into dedicated middleware functions.\n\nKey changes:\n- Extracted JWT validation into its own module\n- Added refresh token rotation\n- Updated tests\n\nNo rush but would love to get it merged before Friday's release.",
    threadId: "t5",
    priority: "action_needed",
    priorityScore: 65,
    priorityReason: "Teammate + PR review request + upcoming release deadline",
    sentiment: "positive",
    aiContextNote: "Teammate \u00b7 frequent collaborator \u00b7 PR blocks Friday release",
    receivedAt: ago(90),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m6",
    platform: "discord",
    sender: contacts.alex,
    subject: "Community moderation needed",
    preview: "We've had some heated discussions in #general about the recent pricing changes. A few messages are borderline TOS violations. Could use your input on how to handle.",
    content: "Hey,\n\nHeads up -- we've had some heated discussions in #general about the recent pricing changes. A few messages are borderline TOS violations.\n\nNothing requiring immediate action, but I'd like your input on:\n1. Should we lock the thread?\n2. Any official response we should post?\n3. Two users might need warnings\n\nI've screenshot the concerning messages. Let me know when you're free to discuss.",
    threadId: "t6",
    priority: "action_needed",
    priorityScore: 60,
    priorityReason: "Community moderation + potential TOS issue + needs decision",
    sentiment: "negative",
    aiContextNote: "Community lead \u00b7 moderation issue \u00b7 pricing backlash",
    receivedAt: ago(120),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m7",
    platform: "gmail",
    sender: contacts.nina,
    subject: "Board seat nomination — Action Required",
    preview: "Following up on our conversation. I need your signed consent form for the board nomination by next Wednesday. Attached is the form.",
    content: "Hi,\n\nFollowing up on our conversation at last month's dinner. I need your signed consent form for the board seat nomination by next Wednesday.\n\nAttached is the form. Please review it with your legal counsel if needed, but the key points are:\n- Standard fiduciary duty acknowledgment\n- Conflict of interest disclosure\n- Commitment to quarterly meetings\n\nHappy to hop on a call if you have questions.\n\nBest,\nNina",
    threadId: "t7",
    priority: "action_needed",
    priorityScore: 78,
    priorityReason: "VIP board member + action keyword + deadline next Wednesday",
    sentiment: "positive",
    aiContextNote: "Board member \u00b7 VIP contact \u00b7 formal request",
    receivedAt: ago(180),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m8",
    platform: "slack",
    sender: contacts.tom,
    subject: "Feature spec review needed",
    preview: "Dropped the v2 feature spec in Notion. Need your sign-off before we scope the sprint on Monday. Key decisions on pages 3-4.",
    content: "Hey,\n\nDropped the v2 feature spec in Notion. Here's the link: [Notion Doc]\n\nNeed your sign-off before we scope the sprint on Monday. The key decisions that need your input are on pages 3-4:\n- Whether to go with WebSocket or SSE for real-time updates\n- The data retention policy for free tier\n- Priority of the mobile companion app\n\nThere's also an open question about the AI model budget. Would love your thoughts.",
    threadId: "t8",
    priority: "action_needed",
    priorityScore: 62,
    priorityReason: "Product lead + review/approval request + Monday deadline",
    sentiment: "neutral",
    aiContextNote: "Product lead \u00b7 sprint planning dependency",
    receivedAt: ago(200),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m9",
    platform: "slack",
    sender: contacts.daniel,
    subject: "Deploy approval for staging",
    preview: "Staging deploy is ready. All tests green. Need one more approval to push to production. Can you review the diff?",
    content: "Staging deploy for v1.4.2 is ready.\n\nAll tests passing:\n- Unit: 342/342 \u2713\n- Integration: 56/56 \u2713\n- E2E: 18/18 \u2713\n\nNeed one more approval to push to production. Can you review the diff? It's mostly the payment flow fixes we discussed.\n\nChangelog:\n- Fixed double-charge bug on retry\n- Added idempotency keys\n- Updated Stripe webhook handler",
    threadId: "t9",
    priority: "action_needed",
    priorityScore: 68,
    priorityReason: "DevOps lead + deployment approval + all tests passing",
    sentiment: "positive",
    aiContextNote: "DevOps lead \u00b7 production deploy pending your approval",
    receivedAt: ago(35),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m10",
    platform: "gmail",
    sender: contacts.sam,
    subject: "NDA Review — Acme Corp Partnership",
    preview: "Please review the attached NDA for the Acme Corp partnership. A few clauses I flagged need your attention before I send it back.",
    content: "Hi,\n\nPlease review the attached NDA for the Acme Corp partnership. I've marked up a few clauses that need your attention:\n\n1. Non-compete clause (Section 7) - seems overly broad\n2. IP assignment (Section 12) - needs clarification on pre-existing IP\n3. Term duration - they want 5 years, we typically do 2\n\nLet me know your thoughts and I'll send the redlined version back to their counsel.\n\nBest,\nSam",
    threadId: "t10",
    priority: "action_needed",
    priorityScore: 58,
    priorityReason: "Legal counsel + NDA review + partnership dependency",
    sentiment: "neutral",
    aiContextNote: "Legal counsel \u00b7 partnership NDA \u00b7 3 flagged clauses",
    receivedAt: ago(300),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m11",
    platform: "slack",
    sender: contacts.kate,
    subject: "Design system update ready",
    preview: "Finished the updated component library in Figma. Need your feedback on the new color tokens before I hand off to engineering.",
    content: "Hey! Finished the updated component library in Figma.\n\nKey updates:\n- New color tokens for the dark mode\n- Updated spacing scale (moved to 4px base)\n- New icon set (200+ icons)\n- Accessibility improvements on all form components\n\nNeed your feedback on the color tokens before I hand off to engineering. Link: [Figma]\n\nAlso, quick question: are we keeping the brutalist aesthetic for v2 or softening it?",
    threadId: "t11",
    priority: "action_needed",
    priorityScore: 55,
    priorityReason: "Designer + feedback request + blocks engineering handoff",
    sentiment: "positive",
    aiContextNote: "Designer \u00b7 design system update \u00b7 needs feedback for handoff",
    receivedAt: ago(250),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },

  // ─ FYI (6) ────────────────────────────────────────────
  {
    id: "m12",
    platform: "telegram",
    sender: contacts.maya,
    subject: "Interesting article on AI agents",
    preview: "Saw this article about AI agent architectures and thought of your project. The section on priority scoring is particularly relevant.",
    content: "Hey!\n\nSaw this article about AI agent architectures and thought of your project. The section on priority scoring using weighted signals is particularly relevant to what you're building.\n\nLink: [Article URL]\n\nNo action needed, just thought you'd find it interesting. Let me know what you think when you get a chance!",
    threadId: "t12",
    priority: "fyi",
    priorityScore: 30,
    priorityReason: "Advisor + informational content + no action required",
    sentiment: "positive",
    aiContextNote: "Advisor \u00b7 shared resource \u00b7 no action needed",
    receivedAt: ago(400),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m13",
    platform: "discord",
    sender: contacts.ryan,
    subject: "Bug report: dark mode flicker",
    preview: "Found a minor UI bug — there's a brief flash of light mode when navigating between pages in dark mode. Not blocking but wanted to document it.",
    content: "Found a minor UI bug.\n\nWhen navigating between pages in dark mode, there's a brief flash of light mode (about 200ms). It's the classic Next.js FOUC issue.\n\nNot blocking anything, just wanted to document it. I think adding `suppressHydrationWarning` and setting the class in a script tag should fix it.\n\nHappy to submit a PR if you want.",
    threadId: "t13",
    priority: "fyi",
    priorityScore: 25,
    priorityReason: "Developer + minor bug report + not blocking",
    sentiment: "neutral",
    aiContextNote: "Developer \u00b7 minor bug report \u00b7 has fix suggestion",
    receivedAt: ago(500),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m14",
    platform: "gmail",
    sender: contacts.lisa,
    subject: "Senior Engineer Role — Thought of You",
    preview: "Hi! I came across your profile and thought you'd be a great fit for a Senior Engineer role at Acme Ventures. Would you be open to a quick chat?",
    content: "Hi!\n\nI came across your profile on LinkedIn and thought you'd be a great fit for a Senior Engineer role at Acme Ventures.\n\nThe role involves:\n- Leading a team of 5 engineers\n- Building AI-powered product features\n- Competitive comp ($220-280K + equity)\n\nWould you be open to a 15-minute introductory chat this week?\n\nBest,\nLisa Park\nTalent Acquisition, Acme Ventures",
    threadId: "t14",
    priority: "fyi",
    priorityScore: 20,
    priorityReason: "Recruiter + job opportunity + low historical engagement",
    sentiment: "positive",
    aiContextNote: "Recruiter \u00b7 first contact \u00b7 job opportunity",
    receivedAt: ago(600),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m15",
    platform: "slack",
    sender: contacts.wei,
    subject: "Feature request: export to CSV",
    preview: "Love the product! One thing that would be super helpful is the ability to export message analytics to CSV. Is that on the roadmap?",
    content: "Hey team!\n\nLove the product so far. One thing that would be super helpful for my workflow is the ability to export message analytics to CSV.\n\nSpecifically:\n- Message volume by platform over time\n- Response time metrics\n- Priority distribution\n\nIs that on the roadmap? Happy to provide more details on the use case if helpful.\n\nThanks!",
    threadId: "t15",
    priority: "fyi",
    priorityScore: 22,
    priorityReason: "Customer + feature request + positive sentiment",
    sentiment: "positive",
    aiContextNote: "Customer \u00b7 feature request \u00b7 happy user",
    receivedAt: ago(700),
    isRead: false,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m16",
    platform: "telegram",
    sender: contacts.omar,
    subject: "Team dinner next Friday?",
    preview: "Thinking of organizing a team dinner next Friday at that Italian place downtown. You in? Need a headcount by Wednesday.",
    content: "Hey!\n\nThinking of organizing a team dinner next Friday at that Italian place downtown we went to last time. Good vibes, great pasta.\n\nYou in? Need a headcount by Wednesday so I can make the reservation.\n\nAlso -- any dietary restrictions I should know about for new team members?",
    threadId: "t16",
    priority: "fyi",
    priorityScore: 28,
    priorityReason: "Co-founder + social/team event + soft deadline Wednesday",
    sentiment: "positive",
    aiContextNote: "Co-founder \u00b7 team event \u00b7 RSVP by Wednesday",
    receivedAt: ago(350),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },
  {
    id: "m17",
    platform: "discord",
    sender: contacts.jess,
    subject: "Weekly community stats",
    preview: "Here are this week's community numbers: 234 new members, 1.2K messages, 89% positive sentiment. Full report in #community-metrics.",
    content: "Weekly community stats for March 10-17:\n\n- New members: 234 (+12% WoW)\n- Total messages: 1,247\n- Active threads: 56\n- Sentiment: 89% positive\n- Top channel: #feature-requests\n- Most active time: 2-4 PM EST\n\nFull report with charts posted in #community-metrics.\n\nNothing concerning this week. The pricing discussion cooled down after Alex posted the official response.",
    threadId: "t17",
    priority: "fyi",
    priorityScore: 18,
    priorityReason: "Moderator + routine weekly report + informational",
    sentiment: "positive",
    aiContextNote: "Community moderator \u00b7 weekly stats report",
    receivedAt: ago(800),
    isRead: true,
    isDone: false,
    snoozedUntil: null,
  },

  // ─ SNOOZED (2) ────────────────────────────────────────
  {
    id: "m18",
    platform: "gmail",
    sender: contacts.jake,
    subject: "Updated portfolio — feedback welcome",
    preview: "Just launched my updated portfolio site. Would love your honest feedback on the new case studies section when you have a moment.",
    content: "Hey!\n\nJust launched my updated portfolio site. Would love your honest feedback on the new case studies section.\n\nSpecifically:\n- Does the project narrative flow well?\n- Are the metrics/outcomes clear?\n- How's the visual design?\n\nNo rush at all. Link: [Portfolio URL]\n\nThanks!",
    threadId: "t18",
    priority: "fyi",
    priorityScore: 15,
    priorityReason: "Vendor + feedback request + no time pressure",
    sentiment: "positive",
    aiContextNote: "Vendor \u00b7 personal portfolio review \u00b7 low priority",
    receivedAt: ago(1200),
    isRead: true,
    isDone: false,
    snoozedUntil: new Date(Date.now() + 24 * 60 * 60 * 1000), // tomorrow
  },
  {
    id: "m19",
    platform: "slack",
    sender: contacts.priya,
    subject: "Team retro notes",
    preview: "Attached the retro notes from today's session. Key takeaways: improve CI/CD pipeline speed, better async communication, and the snack budget discussion.",
    content: "Here are the retro notes from today's session:\n\nWhat went well:\n- Shipped 3 major features on time\n- Zero production incidents this sprint\n- Great cross-team collaboration on the auth refactor\n\nWhat to improve:\n- CI/CD pipeline takes 25 min (target: 10 min)\n- Too many meetings, need more async communication\n- The snack budget debate continues\n\nAction items assigned in Jira. Let me know if I missed anything.",
    threadId: "t19",
    priority: "fyi",
    priorityScore: 12,
    priorityReason: "Teammate + meeting notes + informational",
    sentiment: "neutral",
    aiContextNote: "Teammate \u00b7 sprint retro notes \u00b7 review when free",
    receivedAt: ago(900),
    isRead: true,
    isDone: false,
    snoozedUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // next week
  },
]

// ── Threads ─────────────────────────────────────────────

export const MOCK_THREADS: Record<string, Thread> = {
  t1: {
    id: "t1",
    messages: [
      {
        id: "tm1a",
        senderName: "Sarah Chen",
        isMe: false,
        content: "Hi! Quick question -- are we still on track for the Q3 investor update? The board meeting is scheduled for next Friday.",
        sentAt: ago(10080),
        platform: "gmail",
      },
      {
        id: "tm1b",
        senderName: "You",
        isMe: true,
        content: "Hey Sarah, yes we're working on it. Should have the draft ready by mid-week. I'll loop in the finance team for the revenue numbers.",
        sentAt: ago(9000),
        platform: "gmail",
      },
      {
        id: "tm1c",
        senderName: "Sarah Chen",
        isMe: false,
        content: "Great, thanks! One more thing -- can you include the updated CAC and LTV metrics? A few board members specifically asked for those.",
        sentAt: ago(7200),
        platform: "gmail",
      },
      {
        id: "tm1d",
        senderName: "You",
        isMe: true,
        content: "Will do. I'll add a dedicated slide for unit economics. Anything else?",
        sentAt: ago(5000),
        platform: "gmail",
      },
      {
        id: "tm1e",
        senderName: "Sarah Chen",
        isMe: false,
        content: "That covers it. Looking forward to seeing the deck!",
        sentAt: ago(4800),
        platform: "gmail",
      },
      {
        id: "tm1f",
        senderName: "Sarah Chen",
        isMe: false,
        content: "Hey, just following up on the Q3 investor update deck. The board meeting is Friday and we need the final numbers by EOD Thursday at the latest.\n\nSpecifically, we need:\n- Revenue figures for Q3\n- Updated burn rate\n- Revised growth projections\n\nLet me know if you need any help pulling this together. This is time-sensitive.",
        sentAt: ago(8),
        platform: "gmail",
      },
    ],
    summary: {
      points: [
        "They're asking for the Q3 investor update deck",
        "Mentioned the deadline is this Friday",
        "Need revenue figures, burn rate, and growth projections",
        "Board members specifically want CAC and LTV metrics",
      ],
      tone: "Neutral, professional",
    },
  },
  t2: {
    id: "t2",
    messages: [
      {
        id: "tm2a",
        senderName: "Marcus Rivera",
        isMe: false,
        content: "\u{1F6A8} Production API is returning 503s across all endpoints. Customer complaints coming in through support channels.\n\nNeed someone on this NOW. @oncall team has been paged but no response in 15 minutes.\n\nLooks like it started after the 2:30 PM deployment. We may need to rollback.",
        sentAt: ago(2),
        platform: "slack",
      },
    ],
  },
  t3: {
    id: "t3",
    messages: [
      {
        id: "tm3a",
        senderName: "Elena Kowalski",
        isMe: false,
        content: "Hi, I've reviewed the contract draft you sent over. Most of it looks good, but I have a few questions about the payment terms.",
        sentAt: ago(2880),
        platform: "telegram",
      },
      {
        id: "tm3b",
        senderName: "You",
        isMe: true,
        content: "Hi Elena, happy to clarify. What specific terms are you looking at?",
        sentAt: ago(2800),
        platform: "telegram",
      },
      {
        id: "tm3c",
        senderName: "Elena Kowalski",
        isMe: false,
        content: "The payment schedule in clause 4.2. We discussed NET-30 on our last call, but this says NET-60. Also, I thought we agreed to remove the late penalty clause?",
        sentAt: ago(2750),
        platform: "telegram",
      },
      {
        id: "tm3d",
        senderName: "You",
        isMe: true,
        content: "You're right, those should be updated. Let me get the corrected version from legal and send it over.",
        sentAt: ago(2700),
        platform: "telegram",
      },
      {
        id: "tm3e",
        senderName: "Elena Kowalski",
        isMe: false,
        content: "Hi,\n\nThere's a discrepancy in the contract terms we discussed. Clause 4.2 about the payment schedule doesn't match what was agreed in our last call.\n\nSpecifically:\n- We agreed on NET-30 but the contract says NET-60\n- The penalty clause was supposed to be removed\n\nWe need to resolve this before signing tomorrow morning. Can you get legal to review and send a corrected version today?",
        sentAt: ago(25),
        platform: "telegram",
      },
    ],
    summary: {
      points: [
        "Contract clause 4.2 has wrong payment terms (NET-60 vs agreed NET-30)",
        "Late penalty clause should have been removed",
        "Signing deadline is tomorrow morning",
        "Need corrected version sent today",
      ],
      tone: "Tense but professional",
    },
  },
}

// ── Platform Connections ────────────────────────────────

export const PLATFORM_CONNECTIONS: PlatformConnection[] = [
  {
    platform: "gmail",
    isConnected: false,
    isAvailable: true,
    displayName: "Gmail",
    description: "Emails, threads, and attachments from your Google account",
  },
  {
    platform: "slack",
    isConnected: false,
    isAvailable: true,
    displayName: "Slack",
    description: "Direct messages, channels, and mentions from your workspace",
  },
  {
    platform: "telegram",
    isConnected: false,
    isAvailable: true,
    displayName: "Telegram",
    description: "Private chats, group messages, and bot notifications",
  },
  {
    platform: "discord",
    isConnected: false,
    isAvailable: true,
    displayName: "Discord",
    description: "Server messages, DMs, and thread notifications",
  },
  {
    platform: "whatsapp",
    isConnected: false,
    isAvailable: false,
    displayName: "WhatsApp",
    description: "Personal and group chats \u2014 coming soon",
  },
]

// ── VIP Contacts ────────────────────────────────────────

export const MOCK_VIP_CONTACTS: Contact[] = [contacts.sarah, contacts.nina]
